name: Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [PS3,XBOX-360,PS4,XBOX-ONE,SWITCH,PS5,XBOX-SERIES]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get install -y libpcap-dev
    - name: Make Build
      run: |
        mv src/config-${{ matrix.config }}.h.bak src/config.h
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        mv src/lan-play src/peerplay-cr-client-${{ matrix.config }}
        cd ..
        mv src/config.h src/config-${{ matrix.config }}.h.bak
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: peerplay-cr-client-linux-${{ matrix.config }}
        path: build/src/peerplay-cr-client-${{ matrix.config }}
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [PS3,XBOX-360,PS4,XBOX-ONE,SWITCH,PS5,XBOX-SERIES]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    - name: Make Build
      run: |
        ren src/config-${{ matrix.config }}.h.bak config.h
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        msbuild SwitchLanPlay.sln /p:Configuration=Release /p:Platform=x64
        ren src/Release/lan-play.exe peerplay-cr-client-${{ matrix.config }}.exe
        cd ..
        ren src/config.h config-${{ matrix.config }}.h.bak
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: peerplay-cr-client-windows-${{ matrix.config }}
        path: build/src/Release/peerplay-cr-client-${{ matrix.config }}.exe
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [PS3,XBOX-360,PS4,XBOX-ONE,SWITCH,PS5,XBOX-SERIES]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Make Build
      run: |
        mv src/config-${{ matrix.config }}.h.bak src/config.h
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        mv src/lan-play src/peerplay-cr-client-${{ matrix.config }}
        cd ..
        mv src/config.h src/config-${{ matrix.config }}.h.bak
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: peerplay-cr-client-macos-${{ matrix.config }}
        path: build/src/peerplay-cr-client-${{ matrix.config }}
  combine-artifacts:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    strategy:
      matrix:
        platform: [linux, windows, macos]
        console: [PS3,XBOX-360,PS4,XBOX-ONE,SWITCH,PS5,XBOX-SERIES]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: peerplay-cr-client-${{ matrix.platform }}-${{ matrix.console }}
          path: peerplay-cr-client/software/${{ matrix.platform }}/legacy/
      - name: Create archive
        run: |
          zip -r peerplay-cr-client.zip ./peerplay-cr-client
      - name: Upload combined artifacts
        uses: actions/upload-artifact@v2
        with:
          name: peerplay-cr-client-build
          path: peerplay-cr-client
